version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 8
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - build*/**
  discard-paths: yes
